---
name: Ant

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Ant
        run: ./tools/test-build ant
      - uses: actions/upload-artifact@v3
        # upload just one set of artifacts for easier PR review
        if: ${{ matrix.java }} == 1.8 && ${{ matrix.os }} == "ubuntu-latest"
        with:
          path: artifacts/
          retention-days: 30
